import { Category, Brand, Product, Order, StoreSettings, DailySpecial, CustomerNotification } from '@/types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: "Kerala Superstore",
  tagline: "Your neighbourhood Kerala superstore — authentic groceries & spices delivered across the UK",
  phone: "+44 7749 132122",
  whatsapp: "+44 7749 132122",
  email: "info@keralasuperstores.com",
  address: "4 Wallbrook Drive, Manchester",
  postcode: "M9 8PX",
  freeDeliveryThreshold: 50.00,
  standardDeliveryCharge: 3.99,
  codEnabled: true,
  announcementText: "Free UK Delivery on orders over £50 | 4 Wallbrook Drive, Manchester M9 8PX | Parking at rear"
};

export const CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Rice & Rice Products",
    slug: "rice-and-rice-products",
    description: "Palakkadan Matta, Kaima/Jeerakasala, Ponni & Idli Rice",
    iconName: "Wheat",
    imageUrl: "/categories/rice.jpg",
    itemCount: 28,
    varieties: ["Palakkadan Vadi Matta", "Unda Matta (Round)", "Kaima / Jeerakasala", "Ponni Boiled Rice", "Idli & Dosa Rice"]
  },
  {
    id: "cat-2",
    name: "Pulses & Dal",
    slug: "pulses-and-dal",
    description: "Cherupayar, Vanpayar, Toor Dal, Urad Dal, Kadala",
    iconName: "CircleDot",
    imageUrl: "/categories/pulses.jpg",
    itemCount: 22,
    varieties: ["Cherupayar (Moong)", "Toor Dal (Sambar)", "Brown Kadala", "Urad Dal Whole", "Vanpayar"]
  },
  {
    id: "cat-3",
    name: "Masala & Curry Powders",
    slug: "masala-and-curry-powders",
    description: "Sambar, Fish Curry, Meat Masala, Chicken, Garam Masala",
    iconName: "Flame",
    imageUrl: "/categories/masala.jpg",
    itemCount: 45,
    varieties: ["Sambar Powder", "Meat Masala", "Fish Curry Masala", "Chicken Masala", "Kashmiri Chilli", "Garam Masala"]
  },
  {
    id: "cat-4",
    name: "Breakfast Powders",
    slug: "breakfast-powders",
    description: "Puttu Podi, Appam Podi, Idiyappam Podi, Rava, Wheat",
    iconName: "Coffee",
    imageUrl: "/categories/breakfast.jpg",
    itemCount: 30,
    varieties: ["Chemba Red Puttu Podi", "White Rice Puttu Podi", "Appam & Idiyappam", "Roasted Rava / Suji", "Dosa Podi"]
  },
  {
    id: "cat-5",
    name: "Spices & Whole Condiments",
    slug: "spices-and-whole-condiments",
    description: "Malabar Cardamom, Black Pepper, Cloves, Cinnamon, Star Anise",
    iconName: "Leaf",
    imageUrl: "/categories/spices.jpg",
    itemCount: 34,
    varieties: ["Wayanad Green Cardamom", "Tellicherry Black Pepper", "Whole Cloves (Gramboo)", "Star Anise (Thakkolam)", "Cinnamon Sticks"]
  },
  {
    id: "cat-6",
    name: "Crisps & Snacks",
    slug: "crisps-and-snacks",
    description: "Kerala Banana Chips (Nendran in pure coconut oil), Sharkara Upperi, Mixture",
    iconName: "Cookie",
    imageUrl: "/categories/snacks.jpg",
    itemCount: 38,
    varieties: ["Banana Chips (Coconut Oil)", "Sharkara Upperi", "Kerala Spicy Mixture", "Tapioca Chips", "Jackfruit Chips"]
  },
  {
    id: "cat-7",
    name: "Pure Oils & Ghee",
    slug: "oils-and-ghee",
    description: "Cold Pressed Coconut Oil, Gingelly/Sesame Oil, Malabar Cow Ghee",
    iconName: "Droplet",
    imageUrl: "/categories/oils.jpg",
    itemCount: 16,
    varieties: ["Cold-Pressed Coconut Oil", "Virgin Coconut Oil", "Malabar Cow Ghee", "Gingelly / Sesame Oil"]
  },
  {
    id: "cat-8",
    name: "Traditional Pickles",
    slug: "traditional-pickles",
    description: "Kaduku Mango, Cut Mango, Lime, Tender Mango, Puli Inji",
    iconName: "Jar",
    imageUrl: "/categories/pickles.jpg",
    itemCount: 26,
    varieties: ["Tender Mango (Kadumango)", "Cut Mango Achar", "Lime / Naranga Pickle", "Puli Inji Relish", "Garlic Pickle"]
  },
  {
    id: "cat-9",
    name: "Frozen Delights",
    slug: "frozen-delights",
    description: "Grated Coconut, Tapioca (Kappa), Malabar Parotta, Neyyappam",
    iconName: "Snowflake",
    imageUrl: "/categories/frozen.jpg",
    itemCount: 24,
    varieties: ["Fresh Grated Coconut", "Malabar Layered Parotta", "Sliced Tapioca (Kappa)", "Frozen Snacks"]
  },
  {
    id: "cat-10",
    name: "Traditional Kitchenwares",
    slug: "traditional-kitchenwares",
    description: "Bronze Uruli, Appam Chatti, Puttu Kudam, Chirava",
    iconName: "Utensils",
    imageUrl: "/categories/kitchenwares.jpg",
    itemCount: 18,
    varieties: ["Bronze Uruli (Mannar)", "Stainless Steel Puttu Kudam", "Non-Stick Appam Chatti", "Cast Iron Tawa", "Coconut Scraper (Chirava)"]
  }
];

export const BRANDS: Brand[] = [
  { id: "b-1", name: "Nirapara", slug: "nirapara", productCount: 42 },
  { id: "b-2", name: "Eastern", slug: "eastern", productCount: 56 },
  { id: "b-3", name: "Double Horse", slug: "double-horse", productCount: 48 },
  { id: "b-4", name: "Brahmins", slug: "brahmins", productCount: 35 },
  { id: "b-5", name: "Melam", slug: "melam", productCount: 24 },
  { id: "b-6", name: "Periyar", slug: "periyar", productCount: 29 },
  { id: "b-7", name: "Grandmas", slug: "grandmas", productCount: 19 },
  { id: "b-8", name: "Bravo", slug: "bravo", productCount: 15 },
  { id: "b-9", name: "Kitchen Treasures", slug: "kitchen-treasures", productCount: 31 },
  { id: "b-10", name: "KLF Coconad", slug: "klf-coconad", productCount: 12 },
  { id: "b-11", name: "Pavizham", slug: "pavizham", productCount: 18 },
  { id: "b-12", name: "Kannan Devan", slug: "kannan-devan", productCount: 8 }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Nirapara Palakkadan Matta Rice (Vadi)",
    slug: "nirapara-palakkadan-matta-rice-5kg",
    brand: "Nirapara",
    category: "Rice & Rice Products",
    categorySlug: "rice-and-rice-products",
    sizeWeight: "5 kg",
    price: 8.99,
    offerPrice: 7.99,
    stock: 45,
    lowStockThreshold: 10,
    barcode: "8901234560011",
    description: "Premium quality Palakkadan Matta Rice parboiled to retain natural dietary nutrients and rich red bran fiber. Essential staple for traditional Kerala lunch with Sambar & Thoran.",
    ingredients: "100% Parboiled Red Matta Rice",
    allergens: ["Naturally Gluten Free"],
    tags: ["matta rice", "palakkad", "red rice", "nirapara", "staple"],
    imageUrl: "/products/matta-rice.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Palakkad, Kerala, India",
    seoTitle: "Nirapara Palakkadan Matta Rice 5kg UK | Kerala Super Store",
    seoDescription: "Buy authentic Nirapara Palakkadan Matta Rice 5kg in the UK.",
    createdAt: "2026-01-10T10:00:00Z"
  },
  {
    id: "prod-2",
    name: "Eastern Kerala Sambar Powder",
    slug: "eastern-kerala-sambar-powder-250g",
    brand: "Eastern",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "250 g",
    price: 2.49,
    offerPrice: 1.99,
    stock: 82,
    lowStockThreshold: 15,
    barcode: "8901234560028",
    description: "Signature aromatic roasted blend of Coriander, Chilli, Fenugreek, Asafoetida and roasted lentils for the perfect Nadan Kerala Sambar.",
    ingredients: "Coriander, Chilli, Fenugreek, Bengal Gram Dal, Turmeric, Cumin, Asafoetida, Salt, Curry Leaves",
    allergens: ["May contain traces of Mustard and Sesame"],
    tags: ["sambar powder", "eastern", "curry masala", "kerala sambar"],
    imageUrl: "/products/sambar-powder.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Adimali, Idukki, Kerala",
    seoTitle: "Eastern Kerala Sambar Powder 250g UK",
    seoDescription: "Authentic Eastern Kerala Sambar Masala Powder delivered across UK.",
    createdAt: "2026-01-12T11:00:00Z"
  },
  {
    id: "prod-3",
    name: "Double Horse Chemba Puttu Podi",
    slug: "double-horse-chemba-puttu-podi-1kg",
    brand: "Double Horse",
    category: "Breakfast Powders",
    categorySlug: "breakfast-powders",
    sizeWeight: "1 kg",
    price: 3.49,
    stock: 28,
    lowStockThreshold: 10,
    barcode: "8901234560035",
    description: "Healthy red rice Chemba coarse flour, steamed roasted to perfection for soft, aromatic breakfast Puttu with Kadala Curry or Banana.",
    ingredients: "Roasted Coarse Red Rice Flour",
    allergens: ["Naturally Gluten Free"],
    tags: ["puttu podi", "chemba", "double horse", "breakfast"],
    imageUrl: "/products/puttu-podi.png",
    isFeatured: true,
    isBestseller: false,
    status: "published",
    origin: "Thrissur, Kerala, India",
    seoTitle: "Double Horse Chemba Puttu Podi 1kg | UK Kerala Store",
    seoDescription: "Order Double Horse Roasted Chemba Puttu Podi online in the UK.",
    createdAt: "2026-01-14T14:30:00Z"
  },
  {
    id: "prod-4",
    name: "Bravo Kerala Banana Chips (Pure Coconut Oil)",
    slug: "bravo-kerala-banana-chips-pure-coconut-oil-400g",
    brand: "Bravo",
    category: "Crisps & Snacks",
    categorySlug: "crisps-and-snacks",
    sizeWeight: "400 g",
    price: 4.49,
    offerPrice: 3.99,
    stock: 65,
    lowStockThreshold: 12,
    barcode: "8901234560042",
    description: "Crispy thinly sliced Kerala raw Nendran bananas deep fried in pure cold pressed coconut oil with natural turmeric and sea salt. Unbeatable authentic crunch!",
    ingredients: "Raw Nendran Plantain Banana, Pure Coconut Oil, Salt, Turmeric Powder",
    allergens: ["None", "Vegetarian & Vegan"],
    tags: ["banana chips", "nendrankai", "coconut oil chips", "kerala snacks", "bravo"],
    imageUrl: "/products/banana-chips.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kozhikode, Kerala, India",
    seoTitle: "Authentic Kerala Banana Chips 400g in Coconut Oil UK",
    seoDescription: "Fresh and crunchy Kerala Banana Chips fried in 100% pure coconut oil.",
    createdAt: "2026-01-15T09:15:00Z"
  },
  {
    id: "prod-5",
    name: "Grandmas Traditional Tender Mango Pickle (Kadumango)",
    slug: "grandmas-tender-mango-pickle-400g",
    brand: "Grandmas",
    category: "Traditional Pickles",
    categorySlug: "traditional-pickles",
    sizeWeight: "400 g",
    price: 3.29,
    stock: 34,
    lowStockThreshold: 8,
    barcode: "8901234560059",
    description: "Authentic spicy and tangy Kerala Sadya-style cut tender mango pickle cured in gingelly oil with crushed mustard seeds and fiery red chillies.",
    ingredients: "Tender Mango Pieces, Gingelly (Sesame) Oil, Salt, Red Chilli Powder, Mustard Seeds, Fenugreek, Asafoetida, Turmeric",
    allergens: ["Contains Mustard and Sesame (Natasha's Law declaration)"],
    tags: ["pickle", "mango pickle", "kaduku manga", "grandmas", "achar"],
    imageUrl: "/products/mango-pickle.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "Kottayam, Kerala, India",
    seoTitle: "Grandmas Tender Mango Pickle 400g UK",
    seoDescription: "Authentic Kerala Kadumango Achar in sesame oil delivered across UK.",
    createdAt: "2026-01-18T16:00:00Z"
  },
  {
    id: "prod-6",
    name: "KLF Nirmal Pure Cold-Pressed Coconut Oil",
    slug: "klf-nirmal-pure-coconut-oil-1l",
    brand: "KLF Coconad",
    category: "Pure Oils & Ghee",
    categorySlug: "oils-and-ghee",
    sizeWeight: "1 L",
    price: 5.99,
    offerPrice: 4.99,
    stock: 52,
    lowStockThreshold: 10,
    barcode: "8901234560066",
    description: "100% pure, unrefined cold-pressed edible coconut oil made from sun-dried Kerala copra coconuts. Perfect for authentic Kerala fish curries, thoran, and hair care.",
    ingredients: "100% Pure Coconut Oil",
    allergens: ["Tree Nuts (Coconut)"],
    tags: ["coconut oil", "klf", "pure oil", "cold pressed", "cooking oil"],
    imageUrl: "/products/coconut-oil.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Irinjalakuda, Kerala, India",
    seoTitle: "KLF Nirmal Pure Coconut Oil 1 Litre UK",
    seoDescription: "Buy pure cold pressed KLF Coconut Oil in the UK with fast home delivery.",
    createdAt: "2026-01-20T12:00:00Z"
  },
  {
    id: "prod-7",
    name: "Wayanad Green Cardamom (8mm Bold Grade)",
    slug: "wayanad-green-cardamom-bold-100g",
    brand: "Kitchen Treasures",
    category: "Spices & Whole Condiments",
    categorySlug: "spices-and-whole-condiments",
    sizeWeight: "100 g",
    price: 6.49,
    stock: 22,
    lowStockThreshold: 5,
    barcode: "8901234560073",
    description: "Hand-picked, sun-dried extra bold 8mm emerald green cardamom pods directly from the lush hills of Wayanad, Kerala. Intense fragrance for Payasam, Biriyani & Chai.",
    ingredients: "100% Whole Green Cardamom Pods",
    allergens: ["Naturally Gluten Free"],
    tags: ["cardamom", "elakka", "wayanad", "whole spice", "green cardamom"],
    imageUrl: "/products/cardamom.png",
    isFeatured: true,
    isBestseller: false,
    status: "published",
    origin: "Wayanad, Kerala, India",
    seoTitle: "Wayanad Green Cardamom 8mm Bold 100g UK",
    seoDescription: "Buy authentic Wayanad green cardamom pods in the UK.",
    createdAt: "2026-01-22T08:30:00Z"
  },
  {
    id: "prod-8",
    name: "Shana Frozen Grated Coconut",
    slug: "shana-frozen-grated-coconut-400g",
    brand: "Grandmas",
    category: "Frozen Delights",
    categorySlug: "frozen-delights",
    sizeWeight: "400 g",
    price: 2.19,
    offerPrice: 1.79,
    stock: 40,
    lowStockThreshold: 8,
    barcode: "8901234560080",
    description: "Freshly grated mature coconut, flash-frozen to retain natural sweetness and juicy moisture. Essential for coconut chutneys, Avial, Thoran and Theeyal.",
    ingredients: "Fresh Grated Coconut Flesh",
    allergens: ["Tree Nuts (Coconut)"],
    tags: ["grated coconut", "frozen", "coconut", "chutney", "avial"],
    imageUrl: "/products/grated-coconut.png",
    isFeatured: false,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Frozen Grated Coconut 400g UK | Kerala Super Store",
    seoDescription: "Convenient frozen grated coconut delivered in temperature-controlled packaging.",
    createdAt: "2026-01-25T15:00:00Z"
  },
  {
    id: "prod-9",
    name: "Double Horse Cherupayar (Whole Green Moong)",
    slug: "double-horse-cherupayar-green-moong-1kg",
    brand: "Double Horse",
    category: "Pulses & Dal",
    categorySlug: "pulses-and-dal",
    sizeWeight: "1 kg",
    price: 3.29,
    stock: 36,
    lowStockThreshold: 10,
    barcode: "8901234560097",
    description: "Premium unpolished whole green gram (Cherupayar). Highly nutritious with high protein & fiber. Perfect companion for Kanji (rice porridge) or Cherupayar Curry with Puttu.",
    ingredients: "100% Whole Green Moong Dal",
    allergens: ["Naturally Gluten Free"],
    tags: ["cherupayar", "green gram", "pulses", "double horse", "healthy"],
    imageUrl: "/products/cherupayar.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Double Horse Cherupayar Whole Green Moong 1kg UK",
    seoDescription: "Authentic Cherupayar whole green gram delivered across UK.",
    createdAt: "2026-01-28T11:20:00Z"
  },
  {
    id: "prod-10",
    name: "Traditional Handcrafted Kerala Bronze Uruli (2.5kg)",
    slug: "traditional-kerala-bronze-uruli-2-5kg",
    brand: "Periyar",
    category: "Traditional Kitchenwares",
    categorySlug: "traditional-kitchenwares",
    sizeWeight: "2.5 kg (10 inch)",
    price: 39.99,
    offerPrice: 34.99,
    stock: 8,
    lowStockThreshold: 2,
    barcode: "8901234560103",
    description: "Handcrafted bell metal bronze (Odu) Uruli made by traditional Kerala artisans in Mannar. Ideal for slow-cooking Payasam, Halwa, Varatti and Ayurvedic medicines.",
    ingredients: "Traditional Bell Metal Bronze (Copper & Tin alloy)",
    allergens: ["Food Grade Metallic Cookware"],
    tags: ["uruli", "bronze cookware", "mannar uruli", "traditional utensils", "payasam"],
    imageUrl: "/products/bronze-uruli.png",
    isFeatured: true,
    isBestseller: false,
    isOffer: true,
    status: "published",
    origin: "Mannar, Alappuzha, Kerala",
    seoTitle: "Authentic Kerala Bronze Uruli 2.5kg UK | Traditional Kitchenware",
    seoDescription: "Heavy cast traditional bronze Uruli from Mannar, Kerala for Payasam and Sadhya.",
    createdAt: "2026-02-01T10:00:00Z"
  },
  {
    id: "prod-11",
    name: "Eastern Meat Masala",
    slug: "eastern-meat-masala-200g",
    brand: "Eastern",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "200 g",
    price: 2.29,
    stock: 64,
    lowStockThreshold: 12,
    barcode: "8901234560110",
    description: "A deep aromatic blend of slow-roasted Kerala spices specifically blended for rich Kerala Beef Roast, Mutton Curry and spicy dry fry.",
    ingredients: "Coriander, Chilli, Black Pepper, Turmeric, Cumin, Star Anise, Fennel, Cloves, Cinnamon, Cardamom, Garlic, Nutmeg",
    allergens: ["May contain traces of Mustard and Celery"],
    tags: ["meat masala", "beef roast", "eastern", "kerala spices"],
    imageUrl: "/products/meat-masala.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Eastern Meat Masala 200g UK",
    seoDescription: "Traditional spicy Eastern Meat Masala for Kerala style beef roast.",
    createdAt: "2026-02-03T14:00:00Z"
  },
  {
    id: "prod-12",
    name: "Bravo Sharkara Upperi (Jaggery Banana Chips)",
    slug: "bravo-sharkara-upperi-400g",
    brand: "Bravo",
    category: "Crisps & Snacks",
    categorySlug: "crisps-and-snacks",
    sizeWeight: "400 g",
    price: 4.69,
    offerPrice: 3.99,
    stock: 50,
    lowStockThreshold: 10,
    barcode: "8901234560127",
    description: "Thick quartered Kerala plantain chips double fried in coconut oil and generously coated in caramelized Marayoor jaggery, dried ginger (Chukku) and cumin powder.",
    ingredients: "Raw Plantain Banana, Coconut Oil, Pure Jaggery, Dried Ginger, Cumin, Rice Flour, Cardamom",
    allergens: ["None", "Vegetarian"],
    tags: ["sharkara upperi", "jaggery chips", "sadya", "kerala sweets", "bravo"],
    imageUrl: "/products/sharkara-upperi.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kozhikode, Kerala, India",
    seoTitle: "Bravo Sharkara Upperi 400g UK | Authentic Kerala Sweet Chips",
    seoDescription: "Crunchy Kerala Sadya jaggery coated banana chips delivered UK nationwide.",
    createdAt: "2026-02-05T09:00:00Z"
  },
  {
    id: "prod-13",
    name: "Daily Delight Frozen Kerala Malabar Parotta (5 Pcs)",
    slug: "daily-delight-malabar-parotta-5pcs",
    brand: "Periyar",
    category: "Frozen Delights",
    categorySlug: "frozen-delights",
    sizeWeight: "400 g (5 Pack)",
    price: 2.69,
    stock: 75,
    lowStockThreshold: 15,
    barcode: "8901234560134",
    description: "Flaky, layered and melt-in-the-mouth authentic Malabar Parotta. Simply heat on a hot tawa for 2 minutes and crush by hand for classic street-style layers.",
    ingredients: "Refined Wheat Flour (Maida), Water, Vegetable Oil, Sugar, Salt",
    allergens: ["Contains Cereals containing Gluten (Wheat)"],
    tags: ["malabar parotta", "kerala parotta", "frozen bread", "porotta"],
    imageUrl: "/products/malabar-parotta.png",
    isFeatured: true,
    isBestseller: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Daily Delight Kerala Malabar Parotta 5pk UK",
    seoDescription: "Authentic frozen Malabar layered parottas ready in 2 minutes.",
    createdAt: "2026-02-08T16:30:00Z"
  },
  {
    id: "prod-14",
    name: "Eastern Toor Dal",
    slug: "eastern-toor-dal-1kg",
    brand: "Eastern",
    category: "Pulses & Dal",
    categorySlug: "pulses-and-dal",
    sizeWeight: "1 kg",
    price: 2.89,
    stock: 58,
    lowStockThreshold: 10,
    barcode: "8901234560141",
    description: "Carefully graded, unpolished yellow split pigeon peas. Cooks down to a silky, creamy consistency essential for authentic Kerala Sambar and Parippu Curry.",
    ingredients: "100% Split Yellow Pigeon Peas (Toor Dal)",
    allergens: ["Naturally Gluten Free"],
    tags: ["toor dal", "parippu", "sambar dal", "eastern", "pulses"],
    imageUrl: "/products/toor-dal.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "India",
    seoTitle: "Eastern Toor Dal 1kg UK | Sambar Lentils",
    seoDescription: "Buy premium unpolished Eastern Toor Dal in the UK.",
    createdAt: "2026-02-10T11:00:00Z"
  },
  {
    id: "prod-15",
    name: "Double Horse Jeerakasala Kaima Biriyani Rice",
    slug: "double-horse-jeerakasala-kaima-rice-1kg",
    brand: "Double Horse",
    category: "Rice & Rice Products",
    categorySlug: "rice-and-rice-products",
    sizeWeight: "1 kg",
    price: 3.99,
    offerPrice: 3.49,
    stock: 42,
    lowStockThreshold: 8,
    barcode: "8901234560158",
    description: "Famous short-grain aromatic Kaima (Jeerakasala) rice from Wayanad. The crown jewel of Thalassery & Malabar Biriyani with exquisite natural aroma and soft texture.",
    ingredients: "100% Aromatic Jeerakasala Rice",
    allergens: ["Naturally Gluten Free"],
    tags: ["kaima rice", "jeerakasala", "thalassery biriyani", "biriyani rice", "double horse"],
    imageUrl: "/products/kaima-rice.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Wayanad, Kerala, India",
    seoTitle: "Double Horse Kaima Jeerakasala Biriyani Rice 1kg UK",
    seoDescription: "Original Malabar biriyani rice delivered anywhere in the UK.",
    createdAt: "2026-02-12T13:45:00Z"
  },
  {
    id: "prod-16",
    name: "Stainless Steel Traditional Puttu Maker (Kudam)",
    slug: "stainless-steel-puttu-maker-kudam",
    brand: "Periyar",
    category: "Traditional Kitchenwares",
    categorySlug: "traditional-kitchenwares",
    sizeWeight: "Standard Size",
    price: 14.99,
    stock: 19,
    lowStockThreshold: 4,
    barcode: "8901234560165",
    description: "Heavy-duty food-grade stainless steel Puttu maker with pressure steamer pot, tubular mould and perforated disc. Compatible with both gas and induction cooktops.",
    ingredients: "Food-grade SS 304 Stainless Steel",
    allergens: ["Cookware"],
    tags: ["puttu maker", "puttu kudam", "steamer", "stainless steel", "kitchenware"],
    imageUrl: "/products/puttu-maker.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "India",
    seoTitle: "Stainless Steel Puttu Maker Kudam Set UK",
    seoDescription: "Authentic South Indian Puttu maker suitable for induction and gas stoves.",
    createdAt: "2026-02-15T10:10:00Z"
  },
  {
    id: "prod-17",
    name: "Pavizham Unda Matta Rice",
    slug: "pavizham-unda-matta-rice-5kg",
    brand: "Pavizham",
    category: "Rice & Rice Products",
    categorySlug: "rice-and-rice-products",
    sizeWeight: "5 kg",
    price: 8.49,
    offerPrice: 7.49,
    stock: 38,
    lowStockThreshold: 8,
    barcode: "8901234560172",
    description: "Authentic round-grain (Unda) parboiled red Matta rice from Pavizham. Plump, nutrient-dense grains packed with natural minerals and fibre.",
    ingredients: "Parboiled Round Red Matta Rice",
    allergens: ["Naturally Gluten Free"],
    tags: ["pavizham", "unda matta", "red rice", "kerala rice"],
    imageUrl: "/products/pavizham-rice.png",
    isFeatured: false,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kalady, Kerala, India",
    seoTitle: "Pavizham Unda Matta Rice 5kg UK",
    seoDescription: "Buy Pavizham round red matta rice in Manchester and UK.",
    createdAt: "2026-02-18T10:00:00Z"
  },
  {
    id: "prod-18",
    name: "Melam Fish Curry Masala",
    slug: "melam-fish-curry-masala-200g",
    brand: "Melam",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "200 g",
    price: 2.39,
    stock: 55,
    lowStockThreshold: 10,
    barcode: "8901234560189",
    description: "Classic Travancore and Kottayam style fish curry spice blend with Kashmiri chilli, fenugreek, coriander and turmeric. Ideal for fiery Meen Mulakittathu.",
    ingredients: "Chilli, Coriander, Fenugreek, Turmeric, Black Pepper, Mustard",
    allergens: ["Contains Mustard"],
    tags: ["fish masala", "melam", "meen curry", "kerala fish"],
    imageUrl: "/products/fish-masala.png",
    isFeatured: true,
    isBestseller: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Melam Fish Curry Masala 200g UK",
    seoDescription: "Authentic Kerala Fish Curry spice mix for rich clay-pot curries.",
    createdAt: "2026-02-20T11:30:00Z"
  },
  {
    id: "prod-19",
    name: "Brahmins White Rice Puttu Podi",
    slug: "brahmins-white-rice-puttu-podi-1kg",
    brand: "Brahmins",
    category: "Breakfast Powders",
    categorySlug: "breakfast-powders",
    sizeWeight: "1 kg",
    price: 3.19,
    stock: 40,
    lowStockThreshold: 10,
    barcode: "8901234560196",
    description: "Steam-treated, coarse-ground aromatic white rice flour from Brahmins. Produces feather-light, soft white puttu with freshly grated coconut.",
    ingredients: "Roasted White Rice Flour",
    allergens: ["Naturally Gluten Free"],
    tags: ["brahmins", "puttu podi", "white rice", "breakfast"],
    imageUrl: "/products/appam-podi.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Brahmins White Rice Puttu Podi 1kg UK",
    seoDescription: "Order Brahmins pure roasted white rice puttu podi online in the UK.",
    createdAt: "2026-02-22T09:15:00Z"
  },
  {
    id: "prod-20",
    name: "Nirapara Chicken Masala",
    slug: "nirapara-chicken-masala-200g",
    brand: "Nirapara",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "200 g",
    price: 2.19,
    offerPrice: 1.79,
    stock: 70,
    lowStockThreshold: 12,
    barcode: "8901234560202",
    description: "Rich and fragrant blend of traditional spices for Nadan Kerala Chicken Curry with coconut milk or spicy chicken fry.",
    ingredients: "Coriander, Chilli, Cumin, Black Pepper, Turmeric, Ginger, Garlic, Cloves, Cinnamon",
    allergens: ["May contain traces of Mustard"],
    tags: ["chicken masala", "nirapara", "curry powder"],
    imageUrl: "/products/chicken-masala.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Nirapara Chicken Masala 200g UK",
    seoDescription: "Authentic Nirapara Chicken Masala delivered across Manchester & UK.",
    createdAt: "2026-02-24T14:20:00Z"
  },
  {
    id: "prod-21",
    name: "Tellicherry Bold Black Peppercorns",
    slug: "tellicherry-bold-black-pepper-200g",
    brand: "Kitchen Treasures",
    category: "Spices & Whole Condiments",
    categorySlug: "spices-and-whole-condiments",
    sizeWeight: "200 g",
    price: 4.99,
    stock: 35,
    lowStockThreshold: 6,
    barcode: "8901234560219",
    description: "World-famous Tellicherry Extra Bold black peppercorns from Malabar. Pungent heat with rich floral citrus undertones. King of spices.",
    ingredients: "100% Whole Black Peppercorns (TGSEB Grade)",
    allergens: ["Naturally Gluten Free"],
    tags: ["black pepper", "tellicherry pepper", "malabar pepper", "spices"],
    imageUrl: "/products/black-pepper.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "Thalassery, Kerala, India",
    seoTitle: "Tellicherry Bold Black Pepper 200g UK",
    seoDescription: "High-grade authentic Tellicherry black peppercorns delivered UK wide.",
    createdAt: "2026-02-26T16:00:00Z"
  },
  {
    id: "prod-22",
    name: "Grandmas Kerala Spicy Mixture",
    slug: "grandmas-kerala-spicy-mixture-350g",
    brand: "Grandmas",
    category: "Crisps & Snacks",
    categorySlug: "crisps-and-snacks",
    sizeWeight: "350 g",
    price: 2.99,
    offerPrice: 2.49,
    stock: 48,
    lowStockThreshold: 10,
    barcode: "8901234560226",
    description: "Crunchy tea-time snack featuring spicy sev, roasted peanuts, fried curry leaves, roasted garlic and fried lentils seasoned with red chilli.",
    ingredients: "Gram Flour, Peanuts, Coconut Oil, Curry Leaves, Garlic, Salt, Chilli",
    allergens: ["Contains Peanuts (Natasha's Law declaration)"],
    tags: ["mixture", "kerala mixture", "snacks", "grandmas", "tea snack"],
    imageUrl: "/products/kerala-mixture.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Grandmas Kerala Spicy Mixture 350g UK",
    seoDescription: "Crispy spicy Kerala tea-time mixture with peanuts and curry leaves.",
    createdAt: "2026-02-28T12:00:00Z"
  },
  {
    id: "prod-23",
    name: "Kera Cold Pressed Pure Coconut Oil",
    slug: "kera-cold-pressed-coconut-oil-500ml",
    brand: "KLF Coconad",
    category: "Pure Oils & Ghee",
    categorySlug: "oils-and-ghee",
    sizeWeight: "500 ml",
    price: 3.79,
    stock: 44,
    lowStockThreshold: 8,
    barcode: "8901234560233",
    description: "Pure edible Grade-1 virgin cold-pressed coconut oil. Clear, intensely fragrant, and free from preservatives or chemical refining.",
    ingredients: "100% Pure Virgin Coconut Oil",
    allergens: ["Tree Nuts (Coconut)"],
    tags: ["kera", "coconut oil", "pure oil", "cold pressed"],
    imageUrl: "/products/kera-coconut-oil.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Kera Cold Pressed Pure Coconut Oil 500ml UK",
    seoDescription: "Buy Kera pure coconut oil online in the UK.",
    createdAt: "2026-03-01T10:30:00Z"
  },
  {
    id: "prod-24",
    name: "Eastern Cut Mango Pickle",
    slug: "eastern-cut-mango-pickle-400g",
    brand: "Eastern",
    category: "Traditional Pickles",
    categorySlug: "traditional-pickles",
    sizeWeight: "400 g",
    price: 2.99,
    stock: 36,
    lowStockThreshold: 8,
    barcode: "8901234560240",
    description: "Firm diced raw green mango pieces marinated in sesame oil, roasted fenugreek and spicy red chilli. Crisp, spicy, and perfectly salted.",
    ingredients: "Mango Pieces, Sesame Oil, Salt, Chilli Powder, Mustard, Fenugreek, Asafoetida",
    allergens: ["Contains Mustard and Sesame"],
    tags: ["mango pickle", "eastern", "achar", "cut mango"],
    imageUrl: "/products/cut-mango-pickle.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Eastern Cut Mango Pickle 400g UK",
    seoDescription: "Traditional Kerala Cut Mango Pickle in gingelly oil.",
    createdAt: "2026-03-03T11:00:00Z"
  },
  {
    id: "prod-25",
    name: "Daily Delight Frozen Sliced Tapioca (Kappa)",
    slug: "daily-delight-frozen-sliced-tapioca-1kg",
    brand: "Periyar",
    category: "Frozen Delights",
    categorySlug: "frozen-delights",
    sizeWeight: "1 kg",
    price: 2.49,
    offerPrice: 1.99,
    stock: 50,
    lowStockThreshold: 10,
    barcode: "8901234560257",
    description: "Premium farm-fresh Kerala tapioca (cassava) peeled, cleaned, sliced, and flash frozen. Ready to boil for Kappa Puzhukku with spicy fish curry.",
    ingredients: "100% Peeled Sliced Tapioca (Cassava)",
    allergens: ["Naturally Gluten Free"],
    tags: ["kappa", "tapioca", "frozen kappa", "kerala kappa", "meen curry"],
    imageUrl: "/products/frozen-kappa.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kottayam, Kerala, India",
    seoTitle: "Daily Delight Frozen Tapioca Kappa 1kg UK",
    seoDescription: "Authentic peeled sliced frozen tapioca kappa delivered across UK.",
    createdAt: "2026-03-05T15:20:00Z"
  },
  {
    id: "prod-26",
    name: "Nirapara Brown Kadala (Kala Chana)",
    slug: "nirapara-brown-kadala-1kg",
    brand: "Nirapara",
    category: "Pulses & Dal",
    categorySlug: "pulses-and-dal",
    sizeWeight: "1 kg",
    price: 2.79,
    stock: 45,
    lowStockThreshold: 8,
    barcode: "8901234560264",
    description: "Whole brown chickpeas (Kadala) packed with dietary protein and iron. Essential for classic Kerala Kadala Curry roasted in coconut paste to pair with Puttu or Appam.",
    ingredients: "100% Whole Brown Chickpeas",
    allergens: ["Naturally Gluten Free"],
    tags: ["kadala", "kala chana", "brown chickpeas", "kadala curry", "nirapara"],
    imageUrl: "/products/kadala.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "India",
    seoTitle: "Nirapara Brown Kadala 1kg UK | Kala Chana for Puttu",
    seoDescription: "Authentic brown kadala for classic Kerala breakfast curry.",
    createdAt: "2026-03-08T09:40:00Z"
  },
  {
    id: "prod-27",
    name: "Brahmins Traditional Sambar Powder",
    slug: "brahmins-traditional-sambar-powder-200g",
    brand: "Brahmins",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "200 g",
    price: 2.29,
    stock: 50,
    lowStockThreshold: 10,
    barcode: "8901234560271",
    description: "Specially formulated recipe from Brahmins kitchen using pure roasted spices and toasted dals for an unmistakable temple-style vegetarian Sambar aroma.",
    ingredients: "Coriander, Chilli, Bengal Gram, Fenugreek, Asafoetida, Turmeric, Cumin",
    allergens: ["May contain traces of Mustard and Sesame"],
    tags: ["brahmins", "sambar powder", "curry powder"],
    imageUrl: "/products/brahmins-sambar.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Brahmins Traditional Sambar Powder 200g UK",
    seoDescription: "Temple-style authentic Kerala sambar powder from Brahmins.",
    createdAt: "2026-03-10T14:10:00Z"
  },
  {
    id: "prod-28",
    name: "Malabar Pure Cow Ghee",
    slug: "malabar-pure-cow-ghee-500ml",
    brand: "Grandmas",
    category: "Pure Oils & Ghee",
    categorySlug: "oils-and-ghee",
    sizeWeight: "500 ml",
    price: 7.49,
    offerPrice: 6.49,
    stock: 25,
    lowStockThreshold: 5,
    barcode: "8901234560288",
    description: "Traditional golden granulated cow ghee made by slow simmering cultured butter. Divine aroma for Neychoru (ghee rice), Payasam, and hot rice.",
    ingredients: "100% Clarified Milk Fat (Pure Cow Butterfat)",
    allergens: ["Contains Milk (Dairy)"],
    tags: ["ghee", "cow ghee", "malabar ghee", "neychoru", "dairy"],
    imageUrl: "/products/malabar-ghee.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "Kerala, India",
    seoTitle: "Malabar Pure Cow Ghee 500ml UK",
    seoDescription: "Authentic aromatic granulated cow ghee for ghee rice and sweets.",
    createdAt: "2026-03-12T16:00:00Z"
  },
  {
    id: "prod-29",
    name: "Eastern Kashmiri Chilli Powder",
    slug: "eastern-kashmiri-chilli-powder-250g",
    brand: "Eastern",
    category: "Masala & Curry Powders",
    categorySlug: "masala-and-curry-powders",
    sizeWeight: "250 g",
    price: 2.69,
    stock: 60,
    lowStockThreshold: 12,
    barcode: "8901234560295",
    description: "Pure Kashmiri red chillies ground to a fine powder. Imparts deep crimson ruby colour to gravies and fries with mild, gentle warmth.",
    ingredients: "100% Ground Kashmiri Red Chillies",
    allergens: ["Naturally Gluten Free"],
    tags: ["kashmiri chilli", "chilli powder", "eastern", "spices"],
    imageUrl: "/products/kashmiri-chilli.png",
    isFeatured: false,
    isBestseller: true,
    status: "published",
    origin: "India",
    seoTitle: "Eastern Kashmiri Chilli Powder 250g UK",
    seoDescription: "Rich red Kashmiri chilli powder for natural vibrant colour in curries.",
    createdAt: "2026-03-14T11:20:00Z"
  },
  {
    id: "prod-30",
    name: "Double Horse Roasted Rava",
    slug: "double-horse-roasted-rava-1kg",
    brand: "Double Horse",
    category: "Breakfast Powders",
    categorySlug: "breakfast-powders",
    sizeWeight: "1 kg",
    price: 2.29,
    stock: 42,
    lowStockThreshold: 8,
    barcode: "8901234560301",
    description: "Evenly roasted coarse durum wheat semolina (Rava). Ready to prepare fluffy Kerala Upma, Rava Kesari or crispy Rava Dosa in minutes without lumps.",
    ingredients: "100% Roasted Wheat Semolina (Suji / Rava)",
    allergens: ["Contains Cereals containing Gluten (Wheat)"],
    tags: ["rava", "semolina", "upma", "double horse", "breakfast"],
    imageUrl: "/products/roasted-rava.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "India",
    seoTitle: "Double Horse Roasted Rava 1kg UK",
    seoDescription: "Pre-roasted wheat semolina for quick and delicious Kerala Upma.",
    createdAt: "2026-03-16T13:00:00Z"
  },
  {
    id: "prod-31",
    name: "Grandmas Puli Inji (Tamarind Ginger Chutney)",
    slug: "grandmas-puli-inji-400g",
    brand: "Grandmas",
    category: "Traditional Pickles",
    categorySlug: "traditional-pickles",
    sizeWeight: "400 g",
    price: 3.49,
    stock: 30,
    lowStockThreshold: 6,
    barcode: "8901234560318",
    description: "The indispensable jewel of Kerala Onam & wedding Sadya. A thick dark relish of crushed fresh ginger, green chillies, concentrated tamarind pulp and melted jaggery.",
    ingredients: "Fresh Ginger, Tamarind Paste, Jaggery, Green Chilli, Gingelly Oil, Salt, Mustard Seeds, Curry Leaves",
    allergens: ["Contains Mustard and Sesame"],
    tags: ["puli inji", "inji curry", "sadya", "grandmas", "tamarind ginger"],
    imageUrl: "/products/puli-inji.png",
    isFeatured: true,
    isBestseller: true,
    status: "published",
    origin: "Kottayam, Kerala, India",
    seoTitle: "Grandmas Puli Inji Tamarind Ginger Relish 400g UK",
    seoDescription: "Authentic sweet, sour and spicy Puli Inji for Kerala Sadhya meals.",
    createdAt: "2026-03-18T10:00:00Z"
  },
  {
    id: "prod-32",
    name: "Traditional Appam Chatti with Lid Non-Stick",
    slug: "traditional-appam-chatti-with-lid",
    brand: "Periyar",
    category: "Traditional Kitchenwares",
    categorySlug: "traditional-kitchenwares",
    sizeWeight: "20 cm Diameter",
    price: 16.99,
    stock: 14,
    lowStockThreshold: 3,
    barcode: "8901234560325",
    description: "Concave curved pan designed specifically for swirling and cooking delicate Kerala Palappam and Vellayappam with soft spongy centers and crispy lace borders.",
    ingredients: "Heavy Gauge Aluminium with 3-layer Non-Stick Coating and Steel Lid",
    allergens: ["Cookware"],
    tags: ["appam chatti", "palappam pan", "kitchenware", "periyar"],
    imageUrl: "/products/appam-chatti.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "India",
    seoTitle: "Traditional Appam Chatti Pan with Lid UK",
    seoDescription: "Authentic curved pan for making lacy Kerala Palappams at home.",
    createdAt: "2026-03-20T12:00:00Z"
  },
  {
    id: "prod-33",
    name: "Wayanad Whole Cloves (Gramboo)",
    slug: "wayanad-whole-cloves-100g",
    brand: "Kitchen Treasures",
    category: "Spices & Whole Condiments",
    categorySlug: "spices-and-whole-condiments",
    sizeWeight: "100 g",
    price: 3.99,
    stock: 32,
    lowStockThreshold: 5,
    barcode: "8901234560332",
    description: "Aromatic dried flower buds of Syzygium aromaticum from Wayanad plantations. Rich in essential clove oils with powerful spicy aroma for Biriyani, Masalas and Chai.",
    ingredients: "100% Whole Cloves",
    allergens: ["Naturally Gluten Free"],
    tags: ["cloves", "gramboo", "whole spices", "wayanad"],
    imageUrl: "/products/cloves.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "Wayanad, Kerala, India",
    seoTitle: "Wayanad Whole Cloves 100g UK | Gramboo",
    seoDescription: "Authentic hand-sorted Kerala whole cloves delivered across UK.",
    createdAt: "2026-03-22T14:30:00Z"
  },
  {
    id: "prod-34",
    name: "Kerala Star Anise (Thakkolam)",
    slug: "kerala-star-anise-100g",
    brand: "Kitchen Treasures",
    category: "Spices & Whole Condiments",
    categorySlug: "spices-and-whole-condiments",
    sizeWeight: "100 g",
    price: 3.49,
    stock: 28,
    lowStockThreshold: 5,
    barcode: "8901234560349",
    description: "Whole 8-pointed star anise pods from the Western Ghats. Imparts sweet, liquorice-like fragrance essential for authentic Malabar Dum Biriyani and Garam Masala.",
    ingredients: "100% Whole Star Anise Pods",
    allergens: ["Naturally Gluten Free"],
    tags: ["star anise", "thakkolam", "biriyani spices", "whole condiments"],
    imageUrl: "/products/star-anise.png",
    isFeatured: false,
    isBestseller: false,
    status: "published",
    origin: "Idukki, Kerala, India",
    seoTitle: "Kerala Star Anise 100g UK | Thakkolam",
    seoDescription: "Buy aromatic whole star anise for biriyani and curry blends in the UK.",
    createdAt: "2026-03-24T09:00:00Z"
  },
  {
    id: "prod-35",
    name: "Idhayam Gingelly / Sesame Oil",
    slug: "idhayam-gingelly-sesame-oil-1l",
    brand: "Grandmas",
    category: "Pure Oils & Ghee",
    categorySlug: "oils-and-ghee",
    sizeWeight: "1 L",
    price: 6.99,
    offerPrice: 5.99,
    stock: 35,
    lowStockThreshold: 6,
    barcode: "8901234560356",
    description: "Pure expeller-pressed sesame (Nallenna) oil made with jaggery. Traditional base for authentic spicy Kerala pickles, podi idli seasoning, and medicinal cures.",
    ingredients: "100% Pure Sesame Seed Oil (Gingelly Oil), Jaggery",
    allergens: ["Contains Sesame Seeds (Natasha's Law declaration)"],
    tags: ["gingelly oil", "sesame oil", "nallenna", "pickle oil", "idhayam"],
    imageUrl: "/products/gingelly-oil.png",
    isFeatured: true,
    isBestseller: true,
    isOffer: true,
    status: "published",
    origin: "South India",
    seoTitle: "Idhayam Gingelly Sesame Oil 1 Litre UK",
    seoDescription: "Pure cold-pressed sesame gingelly oil for authentic Kerala pickles and cooking.",
    createdAt: "2026-03-25T11:00:00Z"
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-1001",
    orderNumber: "KSS-UK-4891",
    customerName: "Rahul Menon",
    customerEmail: "rahul.menon@example.co.uk",
    customerPhone: "+44 7700 900123",
    addressLine1: "12 Birchfield Road",
    addressLine2: "Apt 4B",
    city: "Manchester",
    postcode: "M14 6XL",
    deliveryMethod: "standard",
    deliveryCharge: 1.99,
    subtotal: 34.45,
    discount: 0.00,
    total: 36.44,
    paymentMethod: "cash_on_delivery",
    paymentStatus: "pending",
    orderStatus: "out_for_delivery",
    items: [
      {
        productId: "prod-1",
        productName: "Nirapara Palakkadan Matta Rice (Vadi)",
        sizeWeight: "5 kg",
        unitPrice: 7.99,
        quantity: 2,
        totalPrice: 15.98,
        imageUrl: "/products/matta-rice.png"
      },
      {
        productId: "prod-4",
        productName: "Bravo Kerala Banana Chips (Pure Coconut Oil)",
        sizeWeight: "400 g",
        unitPrice: 3.99,
        quantity: 3,
        totalPrice: 11.97,
        imageUrl: "/products/banana-chips.png"
      },
      {
        productId: "prod-2",
        productName: "Eastern Kerala Sambar Powder",
        sizeWeight: "250 g",
        unitPrice: 1.99,
        quantity: 1,
        totalPrice: 1.99,
        imageUrl: "/products/sambar-powder.png"
      },
      {
        productId: "prod-6",
        productName: "KLF Nirmal Pure Cold-Pressed Coconut Oil",
        sizeWeight: "1 L",
        unitPrice: 4.99,
        quantity: 1,
        totalPrice: 4.99,
        imageUrl: "/products/coconut-oil.png"
      }
    ],
    notes: "Please call on arrival, buzzer 4B.",
    createdAt: "2026-03-28T14:20:00Z"
  },
  {
    id: "ord-1002",
    orderNumber: "KSS-UK-4892",
    customerName: "Anju Thomas",
    customerEmail: "anju.thomas@example.co.uk",
    customerPhone: "+44 7700 900456",
    addressLine1: "88 Stockport Road",
    city: "Stockport",
    postcode: "SK4 1AB",
    deliveryMethod: "standard",
    deliveryCharge: 0.00,
    subtotal: 58.90,
    discount: 0.00,
    total: 58.90,
    paymentMethod: "cash_on_delivery",
    paymentStatus: "pending",
    orderStatus: "packed",
    items: [
      {
        productId: "prod-10",
        productName: "Traditional Handcrafted Kerala Bronze Uruli (2.5kg)",
        sizeWeight: "2.5 kg",
        unitPrice: 34.99,
        quantity: 1,
        totalPrice: 34.99,
        imageUrl: "/products/bronze-uruli.png"
      },
      {
        productId: "prod-15",
        productName: "Double Horse Jeerakasala Kaima Biriyani Rice",
        sizeWeight: "1 kg",
        unitPrice: 3.49,
        quantity: 4,
        totalPrice: 13.96,
        imageUrl: "/products/kaima-rice.png"
      },
      {
        productId: "prod-7",
        productName: "Wayanad Green Cardamom (8mm Bold Grade)",
        sizeWeight: "100 g",
        unitPrice: 6.49,
        quantity: 1,
        totalPrice: 6.49,
        imageUrl: "/products/cardamom.png"
      },
      {
        productId: "prod-13",
        productName: "Daily Delight Frozen Kerala Malabar Parotta (5 Pcs)",
        sizeWeight: "400 g",
        unitPrice: 2.69,
        quantity: 2,
        totalPrice: 5.38,
        imageUrl: "/products/malabar-parotta.png"
      }
    ],
    notes: "Leave in safe parcel box if not home.",
    createdAt: "2026-03-29T09:15:00Z"
  }
];

export const INITIAL_DAILY_SPECIALS: DailySpecial[] = [
  {
    id: "spec-1",
    title: "Thalassery Chicken Dum Biriyani (Chef's Special)",
    description: "Authentic slow-dum cooked fragrant Jeerakasala rice, marinated tender chicken pieces, caramelized fried onions, cashews & raisins. Served with raita, lemon date pickle & pappadam.",
    price: 7.99,
    category: "biriyani",
    availableTime: "Fresh Batch • Ready Today from 12:30 PM",
    portionsTotal: 40,
    portionsRemaining: 12,
    isSoldOut: false,
    imageUrl: "/specials/thalassery_chicken_biriyani.jpg",
    badge: "🔥 Hot Kitchen Special",
    createdAt: "2026-03-30T10:00:00Z"
  },
  {
    id: "spec-2",
    title: "Kerala Malabar Porotta & Beef Roast Combo",
    description: "3 freshly pressed flaky layered Malabar porottas served with spicy traditional Kerala dark beef roast slow-cooked with fresh coconut slices (thenga kothu) and curry leaves.",
    price: 8.49,
    category: "curry_bread",
    availableTime: "Hot from Tawa • Ready Today from 3:30 PM",
    portionsTotal: 50,
    portionsRemaining: 18,
    isSoldOut: false,
    imageUrl: "/specials/porotta_beef_roast.jpg",
    badge: "⭐ Bestseller Combo",
    createdAt: "2026-03-30T10:30:00Z"
  },
  {
    id: "spec-3",
    title: "Evening Chaya & Hot Snack Box (Pazham Pori & Vada)",
    description: "2 hot crispy Nendran Pazham Pori (Banana Fritters) + 2 crunchy Masala Parippu Vadas made fresh in pure coconut oil with ginger dip.",
    price: 3.99,
    category: "snacks",
    availableTime: "Fresh Evening Batch • 4:00 PM - 7:00 PM",
    portionsTotal: 60,
    portionsRemaining: 24,
    isSoldOut: false,
    imageUrl: "/categories/snacks.jpg",
    badge: "☕ Evening Chaya Special",
    createdAt: "2026-03-30T11:00:00Z"
  }
];

export const INITIAL_NOTIFICATIONS: CustomerNotification[] = [
  {
    id: "notif-1",
    title: "🍲 Today's Kitchen Alert: Fresh Thalassery Biriyani!",
    message: "Fresh batch of authentic Thalassery Chicken Dum Biriyani is ready at 4 Wallbrook Drive! Limited 40 portions prepared. Order online for Manchester local delivery or store collection.",
    type: "special_item",
    specialItemId: "spec-1",
    timestamp: "10 mins ago",
    isRead: false
  },
  {
    id: "notif-2",
    title: "✈️ Cochin Air Cargo Shipment Arrived!",
    message: "Weekly direct air cargo with fresh Tapioca (Kappa), Nendran bananas, curry leaves, and green chillies has arrived fresh in Manchester.",
    type: "cargo_arrival",
    timestamp: "2 hours ago",
    isRead: false
  },
  {
    id: "notif-3",
    title: "🔥 Flash Weekend Discount Active",
    message: "Up to 25% off selected Matta rice, coconut oils, and Brahmins masala powders. Free UK nationwide delivery on qualifying orders.",
    type: "deal",
    timestamp: "1 day ago",
    isRead: true
  }
];

export const INITIAL_COUPONS: import('@/types').Coupon[] = [
  {
    id: "coup-1",
    code: "M9LOCAL",
    description: "10% off for local Manchester M9 and neighbouring postcodes",
    discountType: "percentage",
    discountValue: 10,
    minSpend: 25.00,
    maxDiscount: 15.00,
    usageCount: 42,
    isActive: true,
    createdAt: "2026-03-01T10:00:00Z"
  },
  {
    id: "coup-2",
    code: "FIRSTORDER",
    description: "£5.00 Flat Off on your first authentic Kerala grocery haul",
    discountType: "fixed",
    discountValue: 5.00,
    minSpend: 35.00,
    usageCount: 88,
    isActive: true,
    createdAt: "2026-03-05T10:00:00Z"
  },
  {
    id: "coup-3",
    code: "ONAM2026",
    description: "15% Special Festival Discount for family orders",
    discountType: "percentage",
    discountValue: 15,
    minSpend: 45.00,
    maxDiscount: 20.00,
    usageCount: 19,
    isActive: true,
    createdAt: "2026-03-15T10:00:00Z"
  },
  {
    id: "coup-4",
    code: "FREESHIP",
    description: "Free Standard UK Delivery on orders over £30",
    discountType: "fixed",
    discountValue: 3.99,
    minSpend: 30.00,
    usageCount: 110,
    isActive: true,
    createdAt: "2026-03-10T10:00:00Z"
  }
];

export const INITIAL_BUNDLES: import('@/types').ComboBundle[] = [
  {
    id: "bundle-1",
    title: "Onam & Vishu Mahasadya Feast Kit",
    subtitle: "Complete authentic 24-dish Sadhya essentials in one box",
    badge: "🌾 Bestseller Festival Kit",
    description: "Includes Palakkadan Matta Rice (5kg), Nendran Sharkara Varatti (500g), Crispy Kerala Banana Chips (500g), Nirapara Sambar Podi (250g), Ada Pradhaman Payasam Mix, Pappadam Pack of 3, and Tender Mango Pickle.",
    items: [
      { name: "Palakkadan Matta Rice", quantity: "5 kg", originalPrice: 10.99 },
      { name: "Authentic Coconut Oil Banana Chips", quantity: "500g", originalPrice: 4.99 },
      { name: "Sharkara Upperi / Varatti", quantity: "500g", originalPrice: 4.99 },
      { name: "Nirapara Sambar Podi", quantity: "250g", originalPrice: 2.79 },
      { name: "Ada Pradhaman Payasam Mix", quantity: "300g", originalPrice: 3.49 },
      { name: "Traditional Kerala Pappadam Pack", quantity: "Pack of 3", originalPrice: 3.99 },
      { name: "Mother's Tender Mango Pickle", quantity: "400g", originalPrice: 3.29 }
    ],
    regularPrice: 34.53,
    bundlePrice: 27.99,
    savingsText: "Save £6.54 (19% OFF)",
    imageUrl: "/branding/kerala-grocery-basket.jpg",
    isActive: true,
    isPopular: true,
    createdAt: "2026-03-15T12:00:00Z"
  },
  {
    id: "bundle-2",
    title: "Malabar Evening Tea & Snack Combo",
    subtitle: "Hot homemade Kerala tea-time snacks & premium dust tea",
    badge: "☕ 4 PM Chaya Time",
    description: "Freshly prepared Crispy Parippu Vada (4 pcs), Sweet Pazhampori (4 pcs), Neyyappam (4 pcs), Spicy Kerala Mixture (300g), and AVT Premium Dust Tea (500g).",
    items: [
      { name: "Fresh Pazhampori (Banana Fritters)", quantity: "4 pieces", originalPrice: 3.99 },
      { name: "Neyyappam (Ghee Appam)", quantity: "4 pieces", originalPrice: 3.99 },
      { name: "Crunchy Parippu Vada", quantity: "4 pieces", originalPrice: 3.49 },
      { name: "Kerala Mixture (Spicy)", quantity: "300g", originalPrice: 2.99 },
      { name: "AVT Premium Dust Tea", quantity: "500g", originalPrice: 4.49 }
    ],
    regularPrice: 18.95,
    bundlePrice: 14.50,
    savingsText: "Save £4.45 (23% OFF)",
    imageUrl: "/categories/snacks.jpg",
    isActive: true,
    isPopular: true,
    createdAt: "2026-03-20T12:00:00Z"
  },
  {
    id: "bundle-3",
    title: "UK Malayali Student / Bachelor Starter Pack",
    subtitle: "Must-have Kerala kitchen essentials to get cooking right away",
    badge: "🎓 Student & Newcomer Pack",
    description: "Everything a Malayali student or newcomer needs: Palakkadan Matta Rice (5kg), KLF Pure Coconut Oil (1L), Chemba Puttu Podi (1kg), Brown Kadala (1kg), Eastern Chicken & Fish Curry Masalas.",
    items: [
      { name: "Palakkadan Matta Rice", quantity: "5 kg", originalPrice: 10.99 },
      { name: "KLF Coconad Pure Coconut Oil", quantity: "1 Litre", originalPrice: 5.49 },
      { name: "Nirapara Chemba Puttu Podi", quantity: "1 kg", originalPrice: 2.49 },
      { name: "Brown Kadala (Chickpeas)", quantity: "1 kg", originalPrice: 2.29 },
      { name: "Eastern Chicken Masala", quantity: "100g", originalPrice: 1.49 },
      { name: "Eastern Fish Curry Masala", quantity: "100g", originalPrice: 1.49 }
    ],
    regularPrice: 24.24,
    bundlePrice: 19.99,
    savingsText: "Save £4.25 (18% OFF)",
    imageUrl: "/branding/kerala-grocery-basket.jpg",
    isActive: true,
    isPopular: false,
    createdAt: "2026-03-22T12:00:00Z"
  }
];

export const INITIAL_RESTOCK_LEADS: import('@/types').RestockLead[] = [
  {
    id: "lead-1",
    productId: "p-matta-10",
    productName: "Double Horse Palakkadan Vadi Matta Rice (10kg)",
    productImage: "/categories/rice.jpg",
    customerName: "Ajayan K.",
    customerPhone: "+447911123456",
    customerEmail: "ajayan.k@gmail.com",
    createdAt: "2026-03-28T14:30:00Z",
    status: "pending"
  },
  {
    id: "lead-2",
    productId: "p-kappa-frozen",
    productName: "Daily Fresh Boiled & Cut Tapioca / Kappa (1kg)",
    productImage: "/branding/kerala-grocery-basket.jpg",
    customerName: "Deepa Menon",
    customerPhone: "+447822654321",
    customerEmail: "deepa.m@outlook.com",
    createdAt: "2026-03-29T09:15:00Z",
    status: "pending"
  },
  {
    id: "lead-3",
    productId: "p-kera-oil",
    productName: "Kera Virgin Cold Pressed Coconut Oil (500ml)",
    productImage: "/categories/oil.jpg",
    customerName: "Sreejith P.",
    customerPhone: "+447700987654",
    customerEmail: "sreejith.p@gmail.com",
    createdAt: "2026-03-27T16:45:00Z",
    status: "notified"
  }
];

